### ISSUE TITLE
Incorrectly identified display

### ISSUE THREAD

**Issue by todd-herbert** [kristianlm/eink-heltec-atmega328#1]
Having just dealt with the same issue, I would like to mention that the fact that your display has labeled pins suggests that is instead the V2 display, based on the QYEG0213RWS800.

I believe the correct datasheet is: https://resource.heltec.cn/download/e-ink/213/2.13b%26w%26r/QYEG0213RWS800/QYEG0213RWS800F13_V1.2.pdf

**Comment by kristianlm** [comment]
Thank you for looking this up and giving feedback, Todd. Better late than never, I suppose ...
